d={}
name=input("enter name: ")
lang=input("enter language: ")
d.update({name:lang})
name=input("enter name: ")
lang=input("enter language: ")
d.update({name:lang})
name=input("enter name: ")
lang=input("enter language: ")
d.update({name:lang})
name=input("enter name: ")
lang=input("enter language: ")
d.update({name:lang})
print(d)