s=set()

num=int(input("enter number "))
s.add(num)
num=int(input("enter number "))
s.add(num)
num=int(input("enter number ")) 
s.add(num)
num=int(input("enter number "))
s.add(num)

# num=input("enter number ")
# s.add(int(num))
# num=input("enter number ")
# s.add(int(num))
# num=input("enter number ")
# s.add(int(num))
# num=input("enter number ")
# s.add(int(num))
print(s)