marks=[]
std1=int(input("enter your marks :"))
marks.append(std1)
std2=int(input("enter your marks :"))
marks.append(std2)
std3=int(input("enter your marks :"))
marks.append(std3)
std4=int(input("enter your marks :"))
marks.append(std4)
std5=int(input("enter your marks :"))
marks.append(std5)
std6=int(input("enter your marks :"))
marks.append(std6)
print(marks)
marks.sort()
print(marks)