fruits=["apple",23.7,"mango",23,"orange"]
print(type(fruits))
print(len(fruits))
print(fruits)
print("-------- methods of Lists ------- ")
print(fruits)
fruits.append("aftab")
print("append = " ,fruits)
num=[2,4,3,43,12,1]
print(num)
fruits.extend(num)
print("extend = " ,fruits)
num.reverse()
print("reverse = " ,num)
num.sort()
print("sort = " ,num)
num.insert(2,22)
print("insert = " ,num)
# num.index(4)
print("index = " ,num.index(43))